services:
  db:
    image: postgres:latest
    ports:
      - "5432:${DB_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_NAME=${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/14.19-trixie/main
